## Data Wrangling Project
### 1. NUFORC Data Scraper  
Travis Letsch

In [1]:
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException
from selenium.common.exceptions import NoSuchElementException
from webdriver_manager.chrome import ChromeDriverManager
import time
import random

<br>

## Overview
This is the first of three notebooks for this project. This notebook will scrape the 2023, 2024, and 2025 data from the NUFORC database. The CSV files will be used in the second notebook, tletsch_2_data_prep.ipynb to clean the data and prepare it for analysis.

<br>

#### 2023 Scraping Loop

In [2]:
# Initialize the webdriver
browser = webdriver.Chrome()
browser.maximize_window()

In [3]:
# Create empty lists to store the scraped data
occurred = []
city = []
state = []
country = []
shape = []
summary = []

In [4]:
# Loop to scrape the NUFORC website
wait = WebDriverWait(browser, 10)

# Range 1-13 to capture all 12 months of data
for month_begin in range(1, 13):
    month_str = f"{month_begin:02d}"

    # Updaute 202(3) in the URL to switch years
    url = f"https://nuforc.org/subndx/?id=e2023{month_str}"

    print(f"Scraping: {url}")

    browser.get(url)
    time.sleep(random.uniform(2, 4))

    # Page counter to track pages for each month of data
    page_num = 1

    while True:
        print(f"  Scraping page {page_num}")
        
        # Wait for table rows to load before scraping
        wait.until(
            EC.presence_of_element_located((By.XPATH, "//table[@id='table_1']/tbody/tr"))
        )

        rows = browser.find_elements(By.XPATH, "//table[@id='table_1']/tbody/tr")

        for row in rows:
            try:
                occurred_date = row.find_element(By.CSS_SELECTOR, "td.column-occurred").text
                sighting_city = row.find_element(By.CSS_SELECTOR, "td.column-city").text
                sighting_state = row.find_element(By.CSS_SELECTOR, "td.column-state").text
                sighting_country = row.find_element(By.CSS_SELECTOR, "td.column-country").text
                ufo_shape = row.find_element(By.CSS_SELECTOR, "td.column-shape").text
                sight_summary = row.find_element(By.CSS_SELECTOR, "td.column-summary").text

                occurred.append(occurred_date)
                city.append(sighting_city)
                state.append(sighting_state)
                country.append(sighting_country)
                shape.append(ufo_shape)
                summary.append(sight_summary)

            except Exception:
                print(f"{month_str}, page {page_num}: row skipped")

        # Find the Next button
        next_button = browser.find_element(By.ID, "table_1_next")

        # Stop if Next button is disabled
        if "disabled" in next_button.get_attribute("class"):
            print(f"  Finished {month_str}")
            break

        # Click next page
        browser.execute_script("arguments[0].click();", next_button)
        
        # The page data loads irregularly. Add a pause to wait for tables to refresh before scraping
        wait.until(EC.staleness_of(rows[0]))  # wait for old rows to disappear

        wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, "#table_1 tbody tr")))

        page_num += 1

Scraping: https://nuforc.org/subndx/?id=e202301
  Scraping page 1
  Scraping page 2
  Scraping page 3
  Scraping page 4
  Finished 01
Scraping: https://nuforc.org/subndx/?id=e202302
  Scraping page 1
  Scraping page 2
  Scraping page 3
  Scraping page 4
  Scraping page 5
  Finished 02
Scraping: https://nuforc.org/subndx/?id=e202303
  Scraping page 1
  Scraping page 2
  Scraping page 3
  Scraping page 4
  Finished 03
Scraping: https://nuforc.org/subndx/?id=e202304
  Scraping page 1
  Scraping page 2
  Scraping page 3
  Scraping page 4
  Finished 04
Scraping: https://nuforc.org/subndx/?id=e202305
  Scraping page 1
  Scraping page 2
  Scraping page 3
  Scraping page 4
  Finished 05
Scraping: https://nuforc.org/subndx/?id=e202306
  Scraping page 1
  Scraping page 2
  Scraping page 3
  Scraping page 4
  Finished 06
Scraping: https://nuforc.org/subndx/?id=e202307
  Scraping page 1
  Scraping page 2
  Scraping page 3
  Scraping page 4
  Scraping page 5
  Scraping page 6
  Finished 07
Scraping: https://nuforc.org/subndx/?id=e202308
  Scraping page 1
  Scraping page 2
  Scraping page 3
  Scraping page 4
  Scraping page 5
  Scraping page 6
  Finished 08
Scraping: https://nuforc.org/subndx/?id=e202309
  Scraping page 1
  Scraping page 2
  Scraping page 3
  Scraping page 4
  Scraping page 5
  Finished 09
Scraping: https://nuforc.org/subndx/?id=e202310
  Scraping page 1
  Scraping page 2
  Scraping page 3
  Scraping page 4
  Scraping page 5
  Finished 10
Scraping: https://nuforc.org/subndx/?id=e202311
  Scraping page 1
  Scraping page 2
  Scraping page 3
  Finished 11
Scraping: https://nuforc.org/subndx/?id=e202312
  Scraping page 1
  Scraping page 2
  Scraping page 3
  Finished 12

<br>

In [5]:
# Populate a DataFrame with the scraped data
nuforc_2023 = pd.DataFrame({
    "occurred": occurred,
    "city": city,
    "state": state,
    "country": country,
    "shape": shape,
    "summary": summary
})

In [6]:
# Display the DataFrame and export it to a CSV file
display(nuforc_2023)

nuforc_2023.to_csv("nuforc_2023.csv", index=False)

,occurred,city,state,country,shape,summary
0,01/31/2023 19:49,Gothenburg,NE,USA,Fireball,Saw trailblazer that moves very rapid and move...
1,01/31/2023 19:15,Sulphur Springs,IN,USA,Circle,Fast spherical orange light
2,01/31/2023 18:38,El Granada,CA,USA,Light,Image of these UFO's were capture with Nikon D...
3,01/31/2023 14:30,Layton,UT,USA,Circle,Working outside with two dozen others looked u...
4,01/31/2023 08:20,Larnaca,Larnaca District,Cyprus,Other,Something like drone
...,...,...,...,...,...,...
4740,12/02/2023 03:45,Great Falls,MT,USA,Light,5+ white lights circling/maneuvering from our ...
4741,12/01/2023 20:45,,TN,USA,Changing,"Witnesses a changing craft, then 3 small human..."
4742,12/01/2023 15:01,Claggan Island,County Mayo,Ireland,Cylinder,Metallic flashing object
4743,12/01/2023 10:25,Albion,ME,USA,Unknown,Spotted a Craft this morning.
4744,12/01/2023 07:13,Kingfisher Close,England,United Kingdom,Flash,flashing object moving erratically/hovering in...

<br>

#### 2024 Scraping Loop

In [7]:
# Create empty lists to store the scraped data
occurred = []
city = []
state = []
country = []
shape = []
summary = []

In [8]:
# Loop to scrape the NUFORC website
wait = WebDriverWait(browser, 10)

# Range 1-13 to capture all 12 months of data
for month_begin in range(1, 13):
    month_str = f"{month_begin:02d}"

    # Updaute 202(4) in the URL to switch years
    url = f"https://nuforc.org/subndx/?id=e2024{month_str}"

    print(f"Scraping: {url}")

    browser.get(url)
    time.sleep(random.uniform(2, 4))

    # Page counter to track pages for each month of data
    page_num = 1

    while True:
        print(f"  Scraping page {page_num}")
        
        # Wait for table rows to load before scraping
        wait.until(
            EC.presence_of_element_located((By.XPATH, "//table[@id='table_1']/tbody/tr"))
        )

        rows = browser.find_elements(By.XPATH, "//table[@id='table_1']/tbody/tr")

        for row in rows:
            try:
                occurred_date = row.find_element(By.CSS_SELECTOR, "td.column-occurred").text
                sighting_city = row.find_element(By.CSS_SELECTOR, "td.column-city").text
                sighting_state = row.find_element(By.CSS_SELECTOR, "td.column-state").text
                sighting_country = row.find_element(By.CSS_SELECTOR, "td.column-country").text
                ufo_shape = row.find_element(By.CSS_SELECTOR, "td.column-shape").text
                sight_summary = row.find_element(By.CSS_SELECTOR, "td.column-summary").text

                occurred.append(occurred_date)
                city.append(sighting_city)
                state.append(sighting_state)
                country.append(sighting_country)
                shape.append(ufo_shape)
                summary.append(sight_summary)

            except Exception:
                print(f"{month_str}, page {page_num}: row skipped")

        # Find the Next button
        next_button = browser.find_element(By.ID, "table_1_next")

        # Stop if Next button is disabled
        if "disabled" in next_button.get_attribute("class"):
            print(f"  Finished {month_str}")
            break

        # Click next page
        browser.execute_script("arguments[0].click();", next_button)
        
        # The page data loads irregularly. Add a pause to wait for tables to refresh before scraping
        wait.until(EC.staleness_of(rows[0]))  # wait for old rows to disappear

        wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, "#table_1 tbody tr")))

        page_num += 1

Scraping: https://nuforc.org/subndx/?id=e202401
  Scraping page 1
  Scraping page 2
  Scraping page 3
  Finished 01
Scraping: https://nuforc.org/subndx/?id=e202402
  Scraping page 1
  Scraping page 2
  Scraping page 3
  Finished 02
Scraping: https://nuforc.org/subndx/?id=e202403
  Scraping page 1
  Scraping page 2
  Scraping page 3
  Finished 03
Scraping: https://nuforc.org/subndx/?id=e202404
  Scraping page 1
  Scraping page 2
  Scraping page 3
  Finished 04
Scraping: https://nuforc.org/subndx/?id=e202405
  Scraping page 1
  Scraping page 2
  Scraping page 3
  Scraping page 4
  Finished 05
Scraping: https://nuforc.org/subndx/?id=e202406
  Scraping page 1
  Scraping page 2
  Scraping page 3
  Finished 06
Scraping: https://nuforc.org/subndx/?id=e202407
  Scraping page 1
  Scraping page 2
  Scraping page 3
  Finished 07
Scraping: https://nuforc.org/subndx/?id=e202408
  Scraping page 1
  Scraping page 2
  Scraping page 3
  Scraping page 4
  Finished 08
Scraping: https://nuforc.org/subndx/?id=e202409
  Scraping page 1
  Scraping page 2
  Scraping page 3
  Finished 09
Scraping: https://nuforc.org/subndx/?id=e202410
  Scraping page 1
  Scraping page 2
  Scraping page 3
  Scraping page 4
  Scraping page 5
  Finished 10
Scraping: https://nuforc.org/subndx/?id=e202411
  Scraping page 1
  Scraping page 2
  Scraping page 3
  Scraping page 4
  Scraping page 5
  Finished 11
Scraping: https://nuforc.org/subndx/?id=e202412
  Scraping page 1
  Scraping page 2
  Scraping page 3
  Scraping page 4
  Scraping page 5
  Scraping page 6
  Scraping page 7
  Scraping page 8
  Scraping page 9
  Scraping page 10
  Finished 12

In [9]:
# Populate a DataFrame with the scraped data
nuforc_2024 = pd.DataFrame({
    "occurred": occurred,
    "city": city,
    "state": state,
    "country": country,
    "shape": shape,
    "summary": summary
})

In [10]:
# Display the DataFrame and export it to a CSV file
display(nuforc_2024)

nuforc_2024.to_csv("nuforc_2024.csv", index=False)

,occurred,city,state,country,shape,summary
0,01/31/2024 23:56,Raleigh,NC,USA,Orb,Saw an orb looking craft over my house
1,01/31/2024 19:30,Houston,TX,USA,Triangle,"It was big, triangular shaped and had multiple..."
2,01/31/2024 19:10,Texarkana,TX,USA,Triangle,Triangle shaped with dim lights on bottom
3,01/31/2024 18:15,Surry,VA,USA,Other,Pyramid shape with lights on one side
4,01/31/2024 03:12,La Salle,IL,USA,Sphere,Light Blue Sphere in the sky shining through m...
...,...,...,...,...,...,...
4248,12/01/2024 14:30,Stephenville,TX,USA,Cube,I thought I heard a helicopter on my home I we...
4249,12/01/2024 12:48,San Diego,CA,USA,Orb,Appeared to be a star but it was daylight so i...
4250,12/01/2024 05:00,Colón,Colón Province,Panama,Triangle,Weird lights in the sky moving in weird format...
4251,12/01/2024 04:08,Motueka,Tasman,New Zealand,Light,"There was cloud cover, object was moving at a ..."
4252,12/01/2024 00:30,Tukwila,WA,USA,Light,Slow-moving light moving low across sky before...

<br>

#### 2025 Scraping Loop

In [11]:
# Create empty lists to store the scraped data
occurred = []
city = []
state = []
country = []
shape = []
summary = []

In [12]:
# Loop to scrape the NUFORC website
wait = WebDriverWait(browser, 10)

# Range 1-13 to capture all 12 months of data
for month_begin in range(1, 13):
    month_str = f"{month_begin:02d}"

    # Updaute 202(5) in the URL to switch years
    url = f"https://nuforc.org/subndx/?id=e2025{month_str}"

    print(f"Scraping: {url}")

    browser.get(url)
    time.sleep(random.uniform(2, 4))

    # Page counter to track pages for each month of data
    page_num = 1

    while True:
        print(f"  Scraping page {page_num}")
        
        # Wait for table rows to load before scraping
        wait.until(
            EC.presence_of_element_located((By.XPATH, "//table[@id='table_1']/tbody/tr"))
        )

        rows = browser.find_elements(By.XPATH, "//table[@id='table_1']/tbody/tr")

        for row in rows:
            try:
                occurred_date = row.find_element(By.CSS_SELECTOR, "td.column-occurred").text
                sighting_city = row.find_element(By.CSS_SELECTOR, "td.column-city").text
                sighting_state = row.find_element(By.CSS_SELECTOR, "td.column-state").text
                sighting_country = row.find_element(By.CSS_SELECTOR, "td.column-country").text
                ufo_shape = row.find_element(By.CSS_SELECTOR, "td.column-shape").text
                sight_summary = row.find_element(By.CSS_SELECTOR, "td.column-summary").text

                occurred.append(occurred_date)
                city.append(sighting_city)
                state.append(sighting_state)
                country.append(sighting_country)
                shape.append(ufo_shape)
                summary.append(sight_summary)

            except Exception:
                print(f"{month_str}, page {page_num}: row skipped")

        # Find the Next button
        next_button = browser.find_element(By.ID, "table_1_next")

        # Stop if Next button is disabled
        if "disabled" in next_button.get_attribute("class"):
            print(f"  Finished {month_str}")
            break

        # Click next page
        browser.execute_script("arguments[0].click();", next_button)
        
        # The page data loads irregularly. Add a pause to wait for tables to refresh before scraping
        wait.until(EC.staleness_of(rows[0]))  # wait for old rows to disappear

        wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, "#table_1 tbody tr")))

        page_num += 1

Scraping: https://nuforc.org/subndx/?id=e202501
  Scraping page 1
  Scraping page 2
  Scraping page 3
  Scraping page 4
  Scraping page 5
  Scraping page 6
  Finished 01
Scraping: https://nuforc.org/subndx/?id=e202502
  Scraping page 1
  Scraping page 2
  Scraping page 3
  Scraping page 4
  Finished 02
Scraping: https://nuforc.org/subndx/?id=e202503
  Scraping page 1
  Scraping page 2
  Scraping page 3
  Scraping page 4
  Finished 03
Scraping: https://nuforc.org/subndx/?id=e202504
  Scraping page 1
  Scraping page 2
  Scraping page 3
  Scraping page 4
  Finished 04
Scraping: https://nuforc.org/subndx/?id=e202505
  Scraping page 1
  Scraping page 2
  Scraping page 3
  Scraping page 4
  Finished 05
Scraping: https://nuforc.org/subndx/?id=e202506
  Scraping page 1
  Scraping page 2
  Scraping page 3
  Finished 06
Scraping: https://nuforc.org/subndx/?id=e202507
  Scraping page 1
  Scraping page 2
  Scraping page 3
  Scraping page 4
  Finished 07
Scraping: https://nuforc.org/subndx/?id=e202508
  Scraping page 1
  Scraping page 2
  Scraping page 3
  Scraping page 4
  Finished 08
Scraping: https://nuforc.org/subndx/?id=e202509
  Scraping page 1
  Scraping page 2
  Scraping page 3
  Scraping page 4
  Finished 09
Scraping: https://nuforc.org/subndx/?id=e202510
  Scraping page 1
  Scraping page 2
  Scraping page 3
  Scraping page 4
  Scraping page 5
  Finished 10
Scraping: https://nuforc.org/subndx/?id=e202511
  Scraping page 1
  Scraping page 2
  Scraping page 3
  Scraping page 4
  Finished 11
Scraping: https://nuforc.org/subndx/?id=e202512
  Scraping page 1
  Scraping page 2
  Scraping page 3
  Finished 12

In [13]:
# Populate a DataFrame with the scraped data
nuforc_2025 = pd.DataFrame({
    "occurred": occurred,
    "city": city,
    "state": state,
    "country": country,
    "shape": shape,
    "summary": summary
})

In [14]:
# Display the DataFrame and export it to a CSV file
display(nuforc_2025)

nuforc_2025.to_csv("nuforc_2025.csv", index=False)

,occurred,city,state,country,shape,summary
0,01/31/2025 23:45,Leicester,England,United Kingdom,Triangle,Felt like time stood still. Appeared to be 3 c...
1,01/31/2025 20:20,Nokomis,FL,USA,Circle,Multiple objects around Venus over an hour lon...
2,01/31/2025 17:50,Nacogdoches,TX,USA,Cylinder,"Cylinder object was traveling above tree line,..."
3,01/31/2025 15:51,San Diego,CA,USA,Cigar,A white pillar / Cigar shaped object moving in...
4,01/31/2025 09:40,,CA,USA,Cigar,Enormous cigar-shaped object hovering over Pal...
...,...,...,...,...,...,...
4484,12/01/2025 19:02,Gebele,,Azerbaijan,Light,"Observed a light looking like a sattelite, but..."
4485,12/01/2025 18:15,Adwick le Street,England,United Kingdom,Oval,Light moving slowly. No sound at all
4486,12/01/2025 17:45,Tolland,CT,USA,Light,Witnessed 3 blue lights move across the sky wi...
4487,12/01/2025 13:00,Dayton,Western Australia,Australia,Unknown,Cloaked aircraft flew over my vehicle
4488,12/01/2025 11:50,Lakewood,CO,USA,Circle,"Circular gray metallic disc hovered silently, ..."